sudo: false
language: python
python:
 - "2.7"
 - "3.5"

install:
  - pip install tox-travis coveralls travis-sphinx

script:
   - tox
   - travis-sphinx build

after_success:
  - coveralls
  - travis-sphinx deploy
