sudo: false
language: python
python:
 - "2.7"
 - "3.5"

install:
  - pip install tox-travis coveralls prospector

script:
   - tox
   - prospector --strictness low lib/*

after_success:
  - coveralls
